### ISSUE TITLE
Tried to start but, 

### ISSUE THREAD

**Issue by DaytradeCentral** [techwithtim/Tower-Defense-Game#1]
### **run.py**
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from main_menu.main_menu import MainMenu
  File "/home/tintin/Tower-Defense-Game/main_menu/main_menu.py", line 1, in <module>
    from game import Game
  File "/home/tintin/Tower-Defense-Game/game.py", line 3, in <module>
    from enemies.scorpion import Scorpion
  File "/home/tintin/Tower-Defense-Game/enemies/scorpion.py", line 11, in <module>
    pygame.image.load(os.path.join("game_assets/enemies/1", "1_enemies_1_run_0" + add_str + ".png")),
pygame.error: Couldn't open game_assets/enemies/1/1_enemies_1_run_000.png

### **game.py**
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "game.py", line 3, in <module>
    from enemies.scorpion import Scorpion
  File "/home/tintin/Tower-Defense-Game/enemies/scorpion.py", line 11, in <module>
    pygame.image.load(os.path.join("game_assets/enemies/1", "1_enemies_1_run_0" + add_str + ".png")),
pygame.error: Couldn't open game_assets/enemies/1/1_enemies_1_run_000.png

**Comment by jsc57x** [comment]
This is not an issue. You should read the readme. You don't have the requested game assets (like it is also shown in the tracebacks). Therefore you are unable to launch the game.
But you can create your own assets and use them :)

**Comment by AlkisPis** [comment]
> This is not an issue. You should read the readme. You don't have the requested game assets (like it is also shown in the tracebacks). Therefore you are unable to launch the game. But you can create your own assets and use them :)

This makes no sense. How can one create **30 own assets** to replace the original ones?  Even if one could do that and the game could still be run, the result would certainly be monstrous.

**Comment by jsc57x** [comment]
Thanks for digging me up. Nobody said it would make sense to create the assets yourself or it does look good then. But this is a possible solution (in fact the updated readme suggest its the ONLY solution...)
