### ISSUE TITLE
could not open game assets?

### ISSUE THREAD

**Issue by AnkithAbhayan** [techwithtim/Tower-Defense-Game#5]
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from main_menu.main_menu import MainMenu
  File "D:\Tower-Defense-Game-master\Tower-Defense-Game-master\main_menu\main_menu.py", line 1, in <module>
    from game import Game
  File "D:\Tower-Defense-Game-master\Tower-Defense-Game-master\game.py", line 3, in <module>
    from enemies.scorpion import Scorpion
  File "D:\Tower-Defense-Game-master\Tower-Defense-Game-master\enemies\scorpion.py", line 11, in <module>
    pygame.image.load(os.path.join("game_assets/enemies/1", "1_enemies_1_run_0" + add_str + ".png")),
pygame.error: Couldn't open game_assets/enemies/1\1_enemies_1_run_000.png

**Comment by shi-ivam** [comment]
He Cannot Release the Game Assets To Public (probly he purchased it from some third party). it is mentioned in the readme.

**Comment by AlkisPis** [comment]
> He Cannot Release the Game Assets To Public (probly he purchased it from some third party). it is mentioned in the readme.

So, why did he published a game with such a huge code? What's the use? Can you find any?
